version: '3.8'
services:
  web-app:
    build: .
    image: date_release
    ports:
    - 8000:8000
    environment:
      MYSQL_HOST: mysql
      MYSQl_USER: root
      MYSQL_PASSWORD: 145100
      MYSQL_DB: date_release_db


  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=date_release_db
      - MYSQL_ROOT_PASSWORD=145100
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


  php:
    image: php:7.0-fpm
    container_name: php-container
    expose:
      - 9000
    volumes:
    - ./www/html/:/var/www/html/




volumes:
  db:
    driver: local